### PR TITLE
Add debug log message for checking test failures.

### PR DESCRIPTION
**Pull request by ramr**
Added a debug log message to check the build.  Thx

### CODE REVIEW

**Comment by ramr** [comment]
@joeferner  not sure how travis gets triggered here on this repo. Only after merge?  Then probably this one needs a merge. Just wanted to check the build output/status.  Thx

**Comment by ramr** [comment]
@joeferner  PTAL Thx. 

I just wanted to ensure that the travis build wasn't flaking out as I could run the test locally with the same versions of the jdk and node (via nvm) and it worked just fine aka no errors.

This is just a debug message but it does need merging in order to trigger off a travis build on the repo.

Thanks.

**Comment by ramr** [comment]
@joeferner forgot to mention here that this is the test log:  
      https://gist.github.com/ramr/c0e6bbb26abdeb0f6584bc5a4a0c549d
(had put it on the old PR) which works just fine. 

I tried this again and I can't reproduce the error. 

I suspect it could well be a build flake. If you can please merge this, can check if travis still fails.  Thanks a ton.

**Comment by ramr** [comment]
@joeferner  Thx. 

Doesn't look like the merge triggered off the build? Is that a manual process? 

Can you please trigger it (can't do it on travis ci). Thx

**Comment by joeferner** [comment]
looks like travis-ci.org is being deprecated, moved to travis-ci.com and it appears to be building correctly

**Comment by ramr** [comment]
Awesome - so probably something flaky in the move. Cool! 
Am glad, was questioning my sanity ... well not any more than I normally do!! ;^)

Could you please create publish a new package on npmjs. Thanks a ton again.

**Pull request merged**
