### PR TITLE
issue with opensdk on arm

### PR DESCRIPTION
**Pull request by egandro**

### CODE REVIEW

**Comment by joeferner** [comment]
Small little fix can you reword without using the word "I"

**Comment by egandro** [comment]
would it be ok for you to make a 0.7.1 version and pubish to npm?

**Comment by joeferner** [comment]
done

**Comment by egandro** [comment]
Thx!

**Comment by egandro** [comment]
May I ask you a question. I might found an issue:

-- java code ---
package com.foo.bar

import com.foo.bar.Reader;
import com.foo.bar.DataReport;

public interface IReportListener {
    public void onReported(Reader reader, DataReport rep);
}

-- node code ---
var myProxy = this.java.newProxy('com.foo.bar.IReportListener ', {
    onReported: function (reader, report) {
        console.log("onReported");;
    }
});

reader.setReportListenerSync(myProxy); 

----

The node code crashes when the reader calls the proxy.

Any idea why? This works fine with simple types like strings an numbers.

**Comment by joeferner** [comment]
I don't see why that shouldn't work.

**Comment by egandro** [comment]
yes ;) me neither - but look what happenes:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff931c9f5fc, pid=9040, tid=0x0000000000002d4c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_92-b14) (build 1.8.0_92-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.92-b14 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [nodejavabridge_bindings.node+0xf5fc]  Java_node_NodeDynamicProxyClass_callJs+0x3c
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\projects\foo\node\hs_err_pid9040.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Pull request merged**
