### PR TITLE
Audit fixes `npm audit fix` for y18n, lodash and hosted-git-info modules

### PR DESCRIPTION
**Pull request by ramr**
@joeferner  PTAL Thx.

Some audit isues that cropped up - fixed via `npm audit fix`.

### CODE REVIEW

**Comment by ramr** [comment]
@joeferner /bump - not sure if you saw this. Could you please publish a dot release to npm? Thanks a ton.

**Comment by joeferner** [comment]
looks like the build is failing, would be nice to fix that before publishing.

**Comment by ramr** [comment]
I can try and take a stab at it. Any clue as to what is failing? 

I did the following to test somewhat based on the readme: 
```git clone <this-repo>; rm -rf node_modules; mkdir node-modules; npm install; npm test```
and that works fine. 

See gist:  https://gist.github.com/ramr/7ae071f32f3c2c3aeb56192ce2695563  for details.

**Comment by ramr** [comment]
Never mind - I see the failure now from the https://www.npmjs.com/package/java  build failing link:
 https://travis-ci.org/github/joeferner/node-java/jobs/774217956  

I'll take a look tomorrow. Thx

**Comment by joeferner** [comment]
I would be OK with dropping node 7 support if it ends up not being an easy fix as well

**Comment by ramr** [comment]
@joeferner  Thx. I'll check if we can fix it first - didn't get much of a chance yesterday but will try over the next few days.

**Comment by ramr** [comment]
Am going to have to dig deeper - the age old developer truism holds true here - it works for me!!

Test log: https://gist.github.com/ramr/c0e6bbb26abdeb0f6584bc5a4a0c549d

Aside: its a pain to install jdk10 from the looks of it (not in xenial repos - had to do it by hand and update alternatives). 

I wonder if it something on the travis end. I will create a test PR just to check the build.

**Comment by ramr** [comment]
Created a test PR to see what the travis results are: https://github.com/joeferner/node-java/pull/526

**Pull request merged**
